//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaSoft.StampClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cfdi.smartweb.com.mx/Timbrado/wsTimbrado.asmx")]
        public string LunaSoft_StampClient_lunasoft_cfdi_timbrado_wsTimbrado {
            get {
                return ((string)(this["LunaSoft_StampClient_lunasoft_cfdi_timbrado_wsTimbrado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cfdi.smartweb.com.mx/Autenticacion/wsAutenticacion.asmx")]
        public string LunaSoft_StampClient_lunasoft_cfdi_autenticacion_wsAutenticacion {
            get {
                return ((string)(this["LunaSoft_StampClient_lunasoft_cfdi_autenticacion_wsAutenticacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cfdi.smartweb.com.mx/Cancelacion/wsCancelacion.asmx")]
        public string LunaSoft_StampClient_lunasoft_cfdi_cancelacion_wsCancelacion {
            get {
                return ((string)(this["LunaSoft_StampClient_lunasoft_cfdi_cancelacion_wsCancelacion"]));
            }
        }
    }
}
