//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace LunaSoft.StampClient.lunasoft.cfdi.autenticacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsAutenticacionSoap", Namespace="http://sufacturacion.com/")]
    public partial class wsAutenticacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AutenticarBasicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticarBasicoBatchProcessOperationCompleted;
        
        private System.Threading.SendOrPostCallback TokenCambioContraseñaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambioContraseñaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsAutenticacion() {
            this.Url = global::LunaSoft.StampClient.Properties.Settings.Default.LunaSoft_StampClient_lunasoft_cfdi_autenticacion_wsAutenticacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AutenticarBasicoCompletedEventHandler AutenticarBasicoCompleted;
        
        /// <remarks/>
        public event AutenticarBasicoBatchProcessCompletedEventHandler AutenticarBasicoBatchProcessCompleted;
        
        /// <remarks/>
        public event TokenCambioContraseñaCompletedEventHandler TokenCambioContraseñaCompleted;
        
        /// <remarks/>
        public event CambioContraseñaCompletedEventHandler CambioContraseñaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sufacturacion.com/AutenticarBasico", RequestNamespace="http://sufacturacion.com/", ResponseNamespace="http://sufacturacion.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AutenticarBasico(string usuario, string password) {
            object[] results = this.Invoke("AutenticarBasico", new object[] {
                        usuario,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarBasicoAsync(string usuario, string password) {
            this.AutenticarBasicoAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void AutenticarBasicoAsync(string usuario, string password, object userState) {
            if ((this.AutenticarBasicoOperationCompleted == null)) {
                this.AutenticarBasicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarBasicoOperationCompleted);
            }
            this.InvokeAsync("AutenticarBasico", new object[] {
                        usuario,
                        password}, this.AutenticarBasicoOperationCompleted, userState);
        }
        
        private void OnAutenticarBasicoOperationCompleted(object arg) {
            if ((this.AutenticarBasicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarBasicoCompleted(this, new AutenticarBasicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sufacturacion.com/AutenticarBasicoBatchProcess", RequestNamespace="http://sufacturacion.com/", ResponseNamespace="http://sufacturacion.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AutenticarBasicoBatchProcess(string usuario, string password) {
            object[] results = this.Invoke("AutenticarBasicoBatchProcess", new object[] {
                        usuario,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarBasicoBatchProcessAsync(string usuario, string password) {
            this.AutenticarBasicoBatchProcessAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void AutenticarBasicoBatchProcessAsync(string usuario, string password, object userState) {
            if ((this.AutenticarBasicoBatchProcessOperationCompleted == null)) {
                this.AutenticarBasicoBatchProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarBasicoBatchProcessOperationCompleted);
            }
            this.InvokeAsync("AutenticarBasicoBatchProcess", new object[] {
                        usuario,
                        password}, this.AutenticarBasicoBatchProcessOperationCompleted, userState);
        }
        
        private void OnAutenticarBasicoBatchProcessOperationCompleted(object arg) {
            if ((this.AutenticarBasicoBatchProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarBasicoBatchProcessCompleted(this, new AutenticarBasicoBatchProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sufacturacion.com/TokenCambioContraseña", RequestNamespace="http://sufacturacion.com/", ResponseNamespace="http://sufacturacion.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TokenCambioContraseña(string apiKey, string email) {
            object[] results = this.Invoke("TokenCambioContraseña", new object[] {
                        apiKey,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TokenCambioContraseñaAsync(string apiKey, string email) {
            this.TokenCambioContraseñaAsync(apiKey, email, null);
        }
        
        /// <remarks/>
        public void TokenCambioContraseñaAsync(string apiKey, string email, object userState) {
            if ((this.TokenCambioContraseñaOperationCompleted == null)) {
                this.TokenCambioContraseñaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTokenCambioContraseñaOperationCompleted);
            }
            this.InvokeAsync("TokenCambioContraseña", new object[] {
                        apiKey,
                        email}, this.TokenCambioContraseñaOperationCompleted, userState);
        }
        
        private void OnTokenCambioContraseñaOperationCompleted(object arg) {
            if ((this.TokenCambioContraseñaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TokenCambioContraseñaCompleted(this, new TokenCambioContraseñaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sufacturacion.com/CambioContraseña", RequestNamespace="http://sufacturacion.com/", ResponseNamespace="http://sufacturacion.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CambioContraseña(string token, string newPassword) {
            this.Invoke("CambioContraseña", new object[] {
                        token,
                        newPassword});
        }
        
        /// <remarks/>
        public void CambioContraseñaAsync(string token, string newPassword) {
            this.CambioContraseñaAsync(token, newPassword, null);
        }
        
        /// <remarks/>
        public void CambioContraseñaAsync(string token, string newPassword, object userState) {
            if ((this.CambioContraseñaOperationCompleted == null)) {
                this.CambioContraseñaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambioContraseñaOperationCompleted);
            }
            this.InvokeAsync("CambioContraseña", new object[] {
                        token,
                        newPassword}, this.CambioContraseñaOperationCompleted, userState);
        }
        
        private void OnCambioContraseñaOperationCompleted(object arg) {
            if ((this.CambioContraseñaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambioContraseñaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AutenticarBasicoCompletedEventHandler(object sender, AutenticarBasicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarBasicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarBasicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AutenticarBasicoBatchProcessCompletedEventHandler(object sender, AutenticarBasicoBatchProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarBasicoBatchProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarBasicoBatchProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TokenCambioContraseñaCompletedEventHandler(object sender, TokenCambioContraseñaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TokenCambioContraseñaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TokenCambioContraseñaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CambioContraseñaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591